import type { Opcodes } from "petals-stem/src/block"

export const English: Record<Uppercase<Opcodes>, string> = {
  "CONTROL_FOREVER": "forever",
  "CONTROL_REPEAT": "repeat %iTIMES;%sSUBSTACK;",
  "CONTROL_IF": "if %iCONDITION; then%sSUBSTACK;",
  "CONTROL_STOP": "stop",
  "CONTROL_WAIT": "wait %iDURATION; seconds",
  "CONTROL_WAIT_UNTIL": "wait until %iCONDITION;",
  "CONTROL_REPEAT_UNTIL": "repeat until %iCONDITION;",
  "CONTROL_WHILE": "while %iCONDITION;%sSUBSTACK;",
  "CONTROL_FOR_EACH": "for each %fVARIABLE; in %iVALUE;",
  "CONTROL_CREATE_CLONE_OF": "create clone of %iCLONE_OPTION;",
  "CONTROL_DELETE_THIS_CLONE": "delete this clone",
  "DATA_SETVARIABLETO": "set %fVARIABLE; to %iVALUE;",
  "DATA_CHANGEVARIABLEBY": "change %fVARIABLE; by %iVALUE;",
  "DATA_SHOWVARIABLE": "show variable %fVARIABLE;",
  "DATA_HIDEVARIABLE": "hide variable %fVARIABLE;",
  "DATA_ADDTOLIST": "add %iITEM; to %fLIST;",
  "DATA_DELETEOFLIST": "delete %iINDEX; of %fLIST;",
  "DATA_DELETEALLOFLIST": "delete all of %fLIST;",
  "DATA_INSERTATLIST": "insert %iITEM; at %iINDEX; of %fLIST;",
  "DATA_REPLACEITEMOFLIST": "replace item %iINDEX; of %fLIST; with %iITEM;",
  "DATA_ITEMOFLIST": "item %iINDEX; of %fLIST;",
  "DATA_ITEMNUMOFLIST": "item # of %iITEM; in %fLIST;",
  "DATA_LENGTHOFLIST": "length of %fLIST;",
  "DATA_LISTCONTAINSITEM": "%fLIST; contains %iITEM;?",
  "DATA_SHOWLIST": "show list %fLIST;",
  "DATA_HIDELIST": "hide list %fLIST;",
  "EVENT_WHENFLAGCLICKED": "when flag clicked",
  "EVENT_WHENTHISSPRITECLICKED": "when this sprite clicked",
  "EVENT_WHENSTAGECLICKED": "when stage clicked",
  "EVENT_WHENBROADCASTRECEIVED": "when I receive %1",
  "EVENT_WHENBACKDROPSWITCHESTO": "when backdrop switches to %1",
  "EVENT_WHENGREATERTHAN": "when %1 > %2",
  "EVENT_BROADCAST": "broadcast %1",
  "EVENT_BROADCASTANDWAIT": "broadcast %1 and wait",
  "EVENT_WHENKEYPRESSED": "when %1 key pressed",
  "LOOKS_SAYFORSECS": "say %1 for %2 seconds",
  "LOOKS_SAY": "say %1",
  "LOOKS_THINKFORSECS": "think %1 for %2 seconds",
  "LOOKS_THINK": "think %1",
  "LOOKS_SHOW": "show",
  "LOOKS_HIDE": "hide",
  "LOOKS_CHANGEEFFECTBY": "change %1 effect by %2",
  "LOOKS_SETEFFECTTO": "set %1 effect to %2",
  "LOOKS_CLEARGRAPHICEFFECTS": "clear graphic effects",
  "LOOKS_CHANGESIZEBY": "change size by %1",
  "LOOKS_SETSIZETO": "set size to %1 %",
  "LOOKS_SWITCHCOSTUMETO": "switch costume to %1",
  "LOOKS_NEXTCOSTUME": "next costume",
  "LOOKS_SWITCHBACKDROPTO": "switch backdrop to %1",
  "LOOKS_GOTOFRONTBACK": "go to %1 layer",
  "LOOKS_GOFORWARDBACKWARDLAYERS": "go %1 %2 layers",
  "LOOKS_BACKDROPNUMBERNAME": "backdrop %1",
  "LOOKS_COSTUMENUMBERNAME": "costume %1",
  "LOOKS_SWITCHBACKDROPTOANDWAIT": "switch backdrop to %1 and wait",
  "LOOKS_NEXTBACKDROP": "next backdrop",
  "MOTION_MOVESTEPS": "move %1 steps",
  "MOTION_TURNLEFT": "turn %1 %2 degrees",
  "MOTION_TURNRIGHT": "turn %1 %2 degrees",
  "MOTION_POINTINDIRECTION": "point in direction %1",
  "MOTION_POINTTOWARDS": "point towards %1",
  "MOTION_GOTO": "go to %1",
  "MOTION_GOTOXY": "go to x: %1 y: %2",
  "MOTION_GLIDESECSTOXY": "glide %1 secs to x: %2 y: %3",
  "MOTION_GLIDETO": "glide %1 secs to %2",
  "MOTION_CHANGEXBY": "change x by %1",
  "MOTION_SETX": "set x to %1",
  "MOTION_CHANGEYBY": "change y by %1",
  "MOTION_SETY": "set y to %1",
  "MOTION_IFONEDGEBOUNCE": "if on edge, bounce",
  "MOTION_SETROTATIONSTYLE": "set rotation style %1",
  "MOTION_XPOSITION": "x position",
  "MOTION_YPOSITION": "y position",
  "MOTION_DIRECTION": "direction",
  "OPERATOR_ADD": "%iNUM1; + %iNUM2;",
  "OPERATOR_SUBTRACT": "%iNUM1; - %iNUM2;",
  "OPERATOR_MULTIPLY": "%iNUM1; * %iNUM2;",
  "OPERATOR_DIVIDE": "%iNUM1; / %iNUM2;",
  "OPERATOR_RANDOM": "pick random %iFROM; to %iTO;",
  "OPERATOR_GT": "%iOPERAND1; > %iOPERAND2;",
  "OPERATOR_LT": "%iOPERAND1; < %iOPERAND2;",
  "OPERATOR_EQUALS": "%iOPERAND1; = %iOPERAND2;",
  "OPERATOR_AND": "%iOPERAND1; and %iOPERAND2;",
  "OPERATOR_OR": "%iOPERAND1; or %iOPERAND2;",
  "OPERATOR_NOT": "not %iOPERAND;",
  "OPERATOR_JOIN": "join %iSTRING1; %iSTRING2;",
  "OPERATOR_LETTER_OF": "letter %iLETTER; of %iSTRING;",
  "OPERATOR_LENGTH": "length of %iSTRING;",
  "OPERATOR_CONTAINS": "%1 contains %2?",
  "OPERATOR_MOD": "%1 mod %2",
  "OPERATOR_MATHOP": "%1 of %2",
  "PROCEDURES_DEFINITION": "define %icustom_block;",
  "SENSING_TOUCHINGOBJECT": "touching %1?",
  "SENSING_TOUCHINGCOLOR": "touching color %1?",
  "SENSING_COLORISTOUCHINGCOLOR": "color %1 is touching %2?",
  "SENSING_DISTANCETO": "distance to %1",
  "SENSING_ASKANDWAIT": "ask %1 and wait",
  "SENSING_ANSWER": "answer",
  "SENSING_KEYPRESSED": "key %1 pressed?",
  "SENSING_MOUSEDOWN": "mouse down?",
  "SENSING_MOUSEX": "mouse x",
  "SENSING_MOUSEY": "mouse y",
  "SENSING_SETDRAGMODE": "set drag mode %1",
  "SENSING_LOUDNESS": "loudness",
  "SENSING_TIMER": "timer",
  "SENSING_RESETTIMER": "reset timer",
  "SENSING_OF": "%1 of %2",
  "SENSING_CURRENT": "current %1",
  "SENSING_DAYSSINCE2000": "days since 2000",
  "SENSING_USERNAME": "username",
  "SOUND_PLAY": "start sound %1",
  "SOUND_PLAYUNTILDONE": "play sound %1 until done",
  "SOUND_STOPALLSOUNDS": "stop all sounds",
  "SOUND_CHANGEEFFECTBY": "change %1 effect by %2",
  "SOUND_CLEAREFFECTS": "clear sound effects",
  "SOUND_CHANGEVOLUMEBY": "change volume by %1",
  "SOUND_SETVOLUMETO": "set volume to %1%",
  "SOUND_VOLUME": "volume",

  // made by @roobscoob, non-official

  "ARGUMENT_REPORTER_BOOLEAN": "%fVALUE;",
  "ARGUMENT_REPORTER_STRING_NUMBER": "%fVALUE;",
  "CONTROL_CREATE_CLONE_OF_MENU": "%1",
  "CONTROL_IF_ELSE": "if %iCONDITION; then%sSUBSTACK;else%sSUBSTACK2;",
  "LOOKS_BACKDROPS": "%1",
  "LOOKS_COSTUME": "%1",
  "MOTION_GLIDETO_MENU": "%1",
  "MOTION_GOTO_MENU": "%1",
  "MOTION_POINTTOWARDS_MENU": "%1",
  "PROCEDURES_PROTOTYPE": "%1",
  "PROCEDURES_CALL": "%1",
  "SENSING_KEYOPTIONS": "%1",
  "SENSING_OF_OBJECT_MENU": "%1",
  "SENSING_DISTANCETOMENU": "%1",
  "SENSING_TOUCHINGOBJECTMENU": "%1",
  "SOUND_SOUNDS_MENU": "%1",
}
