import type { Opcodes } from "petals-stem/src/block"

export const English: Record<Uppercase<Opcodes>, string> = {
  "CONTROL_FOREVER": "forever",
  "CONTROL_REPEAT": "repeat %iTIMES;%sSUBSTACK;",
  "CONTROL_IF": "if %iCONDITION; then%sSUBSTACK;",
  "CONTROL_STOP": "stop",
  "CONTROL_WAIT": "wait %iDURATION; seconds",
  "CONTROL_WAIT_UNTIL": "wait until %iCONDITION;",
  "CONTROL_REPEAT_UNTIL": "repeat until %iCONDITION;",
  "CONTROL_WHILE": "while %iCONDITION;%sSUBSTACK;",
  "CONTROL_FOR_EACH": "for each %fVARIABLE; in %iVALUE;",
  "CONTROL_CREATE_CLONE_OF": "create clone of %iCLONE_OPTION;",
  "CONTROL_DELETE_THIS_CLONE": "delete this clone",
  "DATA_SETVARIABLETO": "set %fVARIABLE; to %iVALUE;",
  "DATA_CHANGEVARIABLEBY": "change %fVARIABLE; by %iVALUE;",
  "DATA_SHOWVARIABLE": "show variable %fVARIABLE;",
  "DATA_HIDEVARIABLE": "hide variable %fVARIABLE;",
  "DATA_ADDTOLIST": "add %iITEM; to %fLIST;",
  "DATA_DELETEOFLIST": "delete %iINDEX; of %fLIST;",
  "DATA_DELETEALLOFLIST": "delete all of %fLIST;",
  "DATA_INSERTATLIST": "insert %iITEM; at %iINDEX; of %fLIST;",
  "DATA_REPLACEITEMOFLIST": "replace item %iINDEX; of %fLIST; with %iITEM;",
  "DATA_ITEMOFLIST": "item %iINDEX; of %fLIST;",
  "DATA_ITEMNUMOFLIST": "item # of %iITEM; in %fLIST;",
  "DATA_LENGTHOFLIST": "length of %fLIST;",
  "DATA_LISTCONTAINSITEM": "%fLIST; contains %iITEM;?",
  "DATA_SHOWLIST": "show list %fLIST;",
  "DATA_HIDELIST": "hide list %fLIST;",
  "EVENT_WHENFLAGCLICKED": "when flag clicked",
  "EVENT_WHENTHISSPRITECLICKED": "when this sprite clicked",
  "EVENT_WHENSTAGECLICKED": "when stage clicked",
  "EVENT_WHENBROADCASTRECEIVED": "when I receive %fBROADCAST_OPTION;",
  "EVENT_WHENBACKDROPSWITCHESTO": "when backdrop switches to %fKEY_OPTION;",
  "EVENT_WHENGREATERTHAN": "when %fWHENGREATERTHANMENU; > %iVALUE;",
  "EVENT_BROADCAST": "broadcast %iBROADCAST_INPUT;",
  "EVENT_BROADCASTANDWAIT": "broadcast %iBROADCAST_INPUT; and wait",
  "EVENT_WHENKEYPRESSED": "when %fKEY_OPTION key pressed",
  "LOOKS_SAYFORSECS": "say %iMESSAGE; for %iSECS; seconds",
  "LOOKS_SAY": "say %iMESSAGE;",
  "LOOKS_THINKFORSECS": "think %iMESSAGE; for %iSECS; seconds",
  "LOOKS_THINK": "think %iMESSAGE;",
  "LOOKS_SHOW": "show",
  "LOOKS_HIDE": "hide",
  "LOOKS_CHANGEEFFECTBY": "change %fEFFECT; effect by %iCHANGE;",
  "LOOKS_SETEFFECTTO": "set %fEFFECT; effect to %iVALUE;",
  "LOOKS_CLEARGRAPHICEFFECTS": "clear graphic effects",
  "LOOKS_CHANGESIZEBY": "change size by %iCHANGE;",
  "LOOKS_SIZE": "size",
  "LOOKS_SETSIZETO": "set size to %iSIZE;",
  "LOOKS_SWITCHCOSTUMETO": "switch costume to %iCOSTUME;",
  "LOOKS_NEXTCOSTUME": "next costume",
  "LOOKS_SWITCHBACKDROPTO": "switch backdrop to %iBACKDROP;",
  "LOOKS_GOTOFRONTBACK": "go to %iLAYER; layer",
  "LOOKS_GOFORWARDBACKWARDLAYERS": "go %fFORWARD_BACKWARD; %iNUM; layers",
  "LOOKS_BACKDROPNUMBERNAME": "backdrop %fNUMBER_NAME;",
  "LOOKS_COSTUMENUMBERNAME": "costume %fNUMBER_NAME;",
  "LOOKS_SWITCHBACKDROPTOANDWAIT": "switch backdrop to %iBACKDROP; and wait",
  "LOOKS_NEXTBACKDROP": "next backdrop",
  "MOTION_MOVESTEPS": "move %iSTEPS; steps",
  "MOTION_TURNLEFT": "turn %iDEGREES; degrees",
  "MOTION_TURNRIGHT": "turn %iDEGREES; degrees",
  "MOTION_POINTINDIRECTION": "point in direction %iDIRECTION;",
  "MOTION_POINTTOWARDS": "point towards %fTOWARDS;",
  "MOTION_GOTO": "go to %fTO;",
  "MOTION_GOTOXY": "go to x: %iX; y: %iY;",
  "MOTION_GLIDESECSTOXY": "glide %iSECS; secs to x: %iX; y: %iY;",
  "MOTION_GLIDETO": "glide %iSECS; secs to %iTO;",
  "MOTION_CHANGEXBY": "change x by %iDX;",
  "MOTION_SETX": "set x to %iX;",
  "MOTION_CHANGEYBY": "change y by %iDY;",
  "MOTION_SETY": "set y to %iY;",
  "MOTION_IFONEDGEBOUNCE": "if on edge, bounce",
  "MOTION_SETROTATIONSTYLE": "set rotation style %fSTYLE;",
  "MOTION_XPOSITION": "x position",
  "MOTION_YPOSITION": "y position",
  "MOTION_DIRECTION": "direction",
  "OPERATOR_ADD": "%iNUM1; + %iNUM2;",
  "OPERATOR_SUBTRACT": "%iNUM1; - %iNUM2;",
  "OPERATOR_MULTIPLY": "%iNUM1; * %iNUM2;",
  "OPERATOR_DIVIDE": "%iNUM1; / %iNUM2;",
  "OPERATOR_RANDOM": "pick random %iFROM; to %iTO;",
  "OPERATOR_GT": "%iOPERAND1; > %iOPERAND2;",
  "OPERATOR_LT": "%iOPERAND1; < %iOPERAND2;",
  "OPERATOR_EQUALS": "%iOPERAND1; = %iOPERAND2;",
  "OPERATOR_AND": "%iOPERAND1; and %iOPERAND2;",
  "OPERATOR_OR": "%iOPERAND1; or %iOPERAND2;",
  "OPERATOR_NOT": "not %iOPERAND;",
  "OPERATOR_JOIN": "join %iSTRING1; %iSTRING2;",
  "OPERATOR_LETTER_OF": "letter %iLETTER; of %iSTRING;",
  "OPERATOR_LENGTH": "length of %iSTRING;",
  "OPERATOR_CONTAINS": "%iSTRING1; contains %iSTRING2;?",
  "OPERATOR_MOD": "%iNUM1; mod %iNUM2;",
  "OPERATOR_MATHOP": "%fOPERATOR; of %iNUM;",
  "PROCEDURES_DEFINITION": "define %icustom_block;",
  "SENSING_TOUCHINGOBJECT": "touching %iTOUCHINGOBJECTMENU;?",
  "SENSING_TOUCHINGCOLOR": "touching color %iCOLOR;?",
  "SENSING_COLORISTOUCHINGCOLOR": "color %iCOLOR; is touching %iCOLOR2;?",
  "SENSING_DISTANCETO": "distance to %iDISTANCETOMENU;",
  "SENSING_ASKANDWAIT": "ask %iQUESTION; and wait",
  "SENSING_ANSWER": "answer",
  "SENSING_KEYPRESSED": "key %iKEY_OPTION; pressed?",
  "SENSING_MOUSEDOWN": "mouse down?",
  "SENSING_MOUSEX": "mouse x",
  "SENSING_MOUSEY": "mouse y",
  "SENSING_SETDRAGMODE": "set drag mode %fDRAG_MODE;",
  "SENSING_LOUDNESS": "loudness",
  "SENSING_TIMER": "timer",
  "SENSING_RESETTIMER": "reset timer",
  "SENSING_OF": "%fPROPERTY; of %iOBJECT;",
  "SENSING_CURRENT": "current %fCURRENTMENU;",
  "SENSING_DAYSSINCE2000": "days since 2000",
  "SENSING_USERNAME": "username",
  "SOUND_PLAY": "start sound %iSOUND;",
  "SOUND_PLAYUNTILDONE": "play sound %iSOUND; until done",
  "SOUND_STOPALLSOUNDS": "stop all sounds",
  "SOUND_CHANGEEFFECTBY": "change %fEFFECT; effect by %iCHANGE;",
  "SOUND_CLEAREFFECTS": "clear sound effects",
  "SOUND_CHANGEVOLUMEBY": "change volume by %iVOLUME;",
  "SOUND_SETVOLUMETO": "set volume to %iVOLUME;%",
  "SOUND_VOLUME": "volume",

  // made by @roobscoob, non-official

  "ARGUMENT_REPORTER_BOOLEAN": "%fVALUE;",
  "ARGUMENT_REPORTER_STRING_NUMBER": "%fVALUE;",
  "CONTROL_CREATE_CLONE_OF_MENU": "%fCLONE_OPTION;",
  "CONTROL_IF_ELSE": "if %iCONDITION; then%sSUBSTACK;else%sSUBSTACK2;",
  "LOOKS_BACKDROPS": "%fBACKDROP;",
  "LOOKS_COSTUME": "%fCOSTUME;",
  "MOTION_GLIDETO_MENU": "%fTO;",
  "MOTION_GOTO_MENU": "%fTO;",
  "MOTION_POINTTOWARDS_MENU": "%iTOWARDS;",
  "PROCEDURES_PROTOTYPE": "%1",
  "PROCEDURES_CALL": "%1",
  "SENSING_KEYOPTIONS": "%fKEY_OPTION;",
  "SENSING_OF_OBJECT_MENU": "%fOBJECT;",
  "SENSING_DISTANCETOMENU": "%fDISTANCETOMENU;",
  "SENSING_TOUCHINGOBJECTMENU": "%fTOUCHINGOBJECTMENU;",
  "SOUND_SOUNDS_MENU": "%fSOUND_MENU;",
}
