import { SwitchBackdropToAndWait as _SwitchBackdropToAndWait } from "./switchBackdropToAndWait";
import { GoForwardBackwardLayers as _GoForwardBackwardLayers } from "./goForwardBackwardLayers";
import { ClearGraphicEffects as _ClearGraphicEffects } from "./clearGraphicEffects";
import { BackdropNumberName as _BackdropNumberName } from "./backdropNumberName";
import { CostumeNumberName as _CostumeNumberName } from "./costumeNumberName";
import { SwitchBackdropTo as _SwitchBackdropTo } from "./switchBackdropTo";
import { SwitchCostumeTo as _SwitchCostumeTo } from "./switchCostumeTo";
import { ChangeEffectBy as _ChangeEffectBy } from "./changeEffectBy";
import { GotoFrontBack as _GotoFrontBack } from "./gotoFrontBack";
import { ChangeSizeBy as _ChangeSizeBy } from "./changeSizeBy";
import { NextBackdrop as _NextBackdrop } from "./nextBackdrop";
import { ThinkForSecs as _ThinkForSecs } from "./thinkForSecs";
import { NextCostume as _NextCostume } from "./nextCostume";
import { SetEffectTo as _SetEffectTo } from "./setEffectTo";
import { SayForSecs as _SayForSecs } from "./sayForSecs";
import { Backdrops as _Backdrops } from "./backdrops";
import { SetSizeTo as _SetSizeTo } from "./setSizeTo";
import { Costume as _Costume } from "./costume";
import { Think as _Think } from "./think";
import { Hide as _Hide } from "./hide";
import { Show as _Show } from "./show";
import { Say as _Say } from "./say";

export namespace Looks {
  export const BackdropNumberName = _BackdropNumberName;
  export const Backdrops = _Backdrops;
  export const ChangeEffectBy = _ChangeEffectBy;
  export const ChangeSizeBy = _ChangeSizeBy;
  export const ClearGraphicEffects = _ClearGraphicEffects;
  export const Costume = _Costume;
  export const CostumeNumberName = _CostumeNumberName;
  export const GoForwardBackwardLayers = _GoForwardBackwardLayers;
  export const GotoFrontBack = _GotoFrontBack;
  export const Hide = _Hide;
  export const NextBackdrop = _NextBackdrop;
  export const NextCostume = _NextCostume;
  export const Say = _Say;
  export const SayForSecs = _SayForSecs;
  export const SetEffectTo = _SetEffectTo;
  export const SetSizeTo = _SetSizeTo;
  export const Show = _Show;
  export const SwitchBackdropTo = _SwitchBackdropTo;
  export const SwitchBackdropToAndWait = _SwitchBackdropToAndWait;
  export const SwitchCostumeTo = _SwitchCostumeTo;
  export const Think = _Think;
  export const ThinkForSecs = _ThinkForSecs;
}
